Update excel-service npm packages
openkfw/TruBudget pull request #1237
Opened 2022-07-21 11:10 UTC by daniel-arnauer

Update all npm packages to newest
Implement breaking changes

Closes parts of #1089

2022-07-21 11:20 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Thu, 21 Jul 2022 11:20:01 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2022-07-21 11:48 UTC, daniel-arnauer commented on excel-export-service/.eslintrc.yaml
> +parser: "@typescript-eslint/parser"
same eslint config as in API

2022-07-21 11:49 UTC, daniel-arnauer commented on api/package.json
> -    "tslint": "*",
deprecated. Eslint is used instead

2022-07-25 09:03 UTC, mayrmartin requested changes
- Consider adding `explicit-function-return-type` to es-lint config & remove comments / todos in es-lint config

2022-07-27 11:13 UTC, mayrmartin approved these changes

2022-07-27 11:13 UTC, merged