1252 additional data
openkfw/TruBudget pull request #1255
Opened 2022-08-04 10:48 UTC by daniel-arnauer

### Checklist

- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/CONTRIBUTING.md).
- [ ] I fixed all necessary PR warnings
- [ ] The commit history is clean
- [ ] The E2E tests are passing
- [ ] If possible, the issue has been divided into more subtasks
- [ ] I did a self review before requesting a review from another team member

### Description

Closes #1252

2022-08-04 10:57 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Thu, 04 Aug 2022 10:57:03 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2022-08-16 07:37 UTC, mayrmartin commented on frontend/src/pages/Common/JsonEditor.js
> +    // console.log("create editor", refContainer.current);
pls remove console.log

2022-08-16 07:37 UTC, mayrmartin commented on frontend/src/pages/Common/JsonEditor.js
> +      // console.log("update props", { content: dataObject, onChange: changeDataCallback });
pls remove console.log

2022-08-16 08:07 UTC, mayrmartin requested changes

2022-08-16 08:07 UTC, mayrmartin commented on frontend/package.json
> +    "jsoneditor": "^9.9.0",
pls remove one of the two JSON editors, only one is used in your code. 
If possible keep `jsoneditor` (more mature), if you prefer to use a wrapper for the `jsoneditor` have a look at [here](https://www.npmjs.com/package/jsoneditor-react) this is a react wrapper for `jsoneditor`

2022-08-17 07:50 UTC, mayrmartin requested changes

2022-08-17 07:50 UTC, mayrmartin commented on frontend/src/api.js
> +  createProject = (displayName, description, thumbnail, projectedBudgets, tags, additionalData = { test: "abc" }) =>
Pls remove the default value. Additional-data field should be empty if not set

2022-08-17 07:50 UTC, mayrmartin commented on scripts/development/docker-compose.yml
> +        API_HOST: 172.20.0.4
For consistency in the project do not change the API_HOST in the dev set-up. Pls reset to `alpha-api`.

2022-08-18 07:38 UTC, daniel-arnauer commented on frontend/src/sagas.js
> +
remove or add to language files

2022-08-18 07:45 UTC, daniel-arnauer commented on e2e-test/cypress/integration/project_edit_spec.js
> +      cy.wait(1000);
remove cy.wait

2022-08-18 07:46 UTC, daniel-arnauer commented on e2e-test/cypress/integration/project_edit_spec.js
> +      }
You can set a shorter test string

2022-08-18 07:47 UTC, daniel-arnauer commented on e2e-test/cypress/integration/project_edit_spec.js
> +      cy.wait(1000);
.

2022-08-18 07:47 UTC, daniel-arnauer commented on e2e-test/cypress/integration/project_edit_spec.js
> +          "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo
.

2022-08-18 07:47 UTC, daniel-arnauer commented on e2e-test/cypress/integration/project_edit_spec.js
> +    cy.wait(1000);
.

2022-08-22 06:30 UTC, mayrmartin requested changes
Pls also remove `TruBudget - Verknüpfung.lnk`

2022-08-22 06:30 UTC, mayrmartin commented on frontend/package.json
> +    "styled-components": "^5.3.5",
pls remove styled-components as ui framework; we only use materiual ui (mui5) for styling

2022-08-22 09:46 UTC, mayrmartin requested changes

2022-08-22 09:46 UTC, mayrmartin commented on frontend/src/pages/Overview/TableView.js
> +  // const additionalDataEmpty = !project.additionalData.test;
pls remove comment if not used

2022-08-22 10:22 UTC, mayrmartin approved these changes

2022-08-22 14:35 UTC, merged