Improvement cookie management
openkfw/TruBudget pull request #1287
Opened 2022-08-26 10:04 UTC by felix2502

### Checklist

- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/CONTRIBUTING.md).
- [ ] I fixed all necessary PR warnings
- [ ] The commit history is clean
- [ ] The E2E tests are passing
- [ ] If possible, the issue has been divided into more subtasks
- [ ] I did a self review before requesting a review from another team member

2022-08-26 14:06 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Fri, 26 Aug 2022 14:06:09 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2022-09-07 09:01 UTC, mayrmartin requested changes

2022-09-07 13:07 UTC, felix2502 commented on email-notification-service/src/middleware.ts
> +  }
An empty String is set, if there is no token and **verifyJWTToken** will throw the error.

2022-09-07 13:15 UTC, felix2502 commented on api/src/httpd/server.ts
> +      }
No token will throw the error below. Setting the token every time is for using multiple accounts on the same browser and providing a new token. Token expiration is handled while creating.

2022-09-07 14:02 UTC, mayrmartin commented on api/src/httpd/server.ts
> +      }
There is no requirement for multiple accounts in the same browser. Creating a new Token on each request is not good practice.
Further: If the token gets replaced on each request, the UI (in our case Axios) should handle this token change as well.

2022-09-07 17:03 UTC, felix2502 commented on api/src/httpd/server.ts
> +      }
A token is only created once when the user logs in, and not on every request. On every request it just checks, whether the cookies have a token set or not, if they do, then the headers are set with that token.

2022-09-14 09:50 UTC, Stezido requested changes
This PR is a breaking change. We only can put it into 3.0.0 with the current changes. Another solution is to still support the old way of storing the JWT token in local storage and remove it with TB 3.0.

2022-09-14 09:50 UTC, Stezido commented on api/src/user_authenticate.ts
> +import { randomString } from "./service/hash";
remove unused imports

2022-10-03 13:25 UTC, Stezido approved these changes
Looks good to me,
I tested the minimal setup using the PRs version for each service.
I also tested it including an old blockchain and export instance (current main).
Good job.

2022-10-03 13:31 UTC, Stezido commented
I rebased the branch onto the latest main branch and added a local docker-compose e2e-test fix

2022-10-04 07:22 UTC, merged