Provisioning: Dynamic user permissions
openkfw/TruBudget pull request #1504
Opened 2023-10-30 11:51 UTC by egdmrsy

### Checklist

- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [ ] I fixed all necessary PR warnings
- [ ] The commit history is clean
- [ ] The E2E tests are passing
- [ ] If possible, the issue has been divided into more subtasks
- [ ] I did a self review before requesting a review from another team member

### Description
Feature: adding dynamic permissions to users in provisioning
Closes #1499

2023-10-30 12:01 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Mon, 30 Oct 2023 12:00:59 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2023-10-30 12:58 UTC, mayrmartin requested changes

2023-10-30 12:58 UTC, mayrmartin commented on provisioning/src/users_and_groups.js
> +    await Promise.allSettled(users.map((user) => { log.info(`~> Adding user ${user.displayName}`); return createUser(axios, {id: user.id, displayName: user.displayName, password: user.password}, orga
what happens if the user is not created correctly? Maybe add some error handling?

2023-10-30 12:58 UTC, mayrmartin commented on provisioning/src/users_and_groups.js
> +        await grantAllPermissionsToUser(axios, user.id);
what happens if the permission can not be granted? Maybe add some error handling?

2023-10-30 12:58 UTC, mayrmartin commented on provisioning/src/users_and_groups.js
> +        await Promise.allSettled(user.permissions.filter(intent => allowedIntents.includes(intent)).map((intent) => { log.info(`~> Granting permission ${intent} to ${user.id}`); return grantGlobalPer
what happens if the permission can not be granted? Maybe add some error handling?

2023-10-30 12:58 UTC, mayrmartin commented on provisioning/src/users_and_groups.js
> +      await Promise.allSettled(group.users.map((user) => addUserToGroup(axios, group.id, user)));
what happens if the user can not be added? Maybe add some error handling?

2023-10-30 12:58 UTC, mayrmartin commented on provisioning/src/users_and_groups.js
> +    await Promise.allSettled(groups.map((group) => createGroup(axios, group)));
what happens if the group can not be created? Maybe add some error handling?

2023-10-30 14:09 UTC, mayrmartin approved these changes

2023-10-30 16:25 UTC, georgimld commented on provisioning/src/users_and_groups.js
> +    const usersWithPermissions = users.filter((user) => Array.isArray(user.permissions) && user.permissions.length > 0);
when would `Array.isArray(user.permissions)` be false?

2023-10-31 12:34 UTC, georgimld approved these changes

2023-10-31 12:44 UTC, merged