1739 refresh token
openkfw/TruBudget pull request #1921
Opened 2024-07-19 08:54 UTC by galethil

### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [x] I fixed all necessary PR warnings
- [x] The commit history is clean
- [ ] The E2E tests are passing
- [x] If possible, the issue has been divided into more subtasks
- [x] I did a self review before requesting a review from another team member

### Description

### How to test

1. Setup necessary env variables
2. Set `REFRESH_TOKEN_STORAGE=db` or `REFRESH_TOKEN_STORAGE=memory`
3. You can shorten the expiration periods of access and refresh token 
4. Test out login and update of access token

Closes #1739

2024-07-19 09:01 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on pipeline 59958 on remote server started</td><td>Fri, 19 Jul 2024 09:01:35 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2024-07-24 15:12 UTC, MartinJurcoGlina requested changes

2024-07-25 06:17 UTC, galethil commented on api/src/config.ts
> +  refreshTokenStorage: string | undefined;
@MartinJurcoGlina using refresh token functionality is optional functionality. That is why there env variables are also optional. I didn't see a reason why admin should define variables for functionality they are not using.

2024-07-25 06:22 UTC, galethil commented on api/src/lib/db.ts
@MartinJurcoGlina we have talked about it with Samo as well. This structure was taken from email service (plus is similar to what we have in AuthBuddy). In case there will be further usages of DB in api service (outside of optional refresh token) we will create a separate task to refactor the whole DB code. Since there are also things like DB migrations missing and other essential parts. For now I was planning to keep it simple.

2024-07-25 07:47 UTC, MartinJurcoGlina commented on api/src/config.ts
> +  refreshTokenStorage: string | undefined;
In my opinion it is a standard functionality and shouldn't be optional. If we want to spare admin of setting a new variable, we can pick one of the options as a default value

2024-07-25 12:06 UTC, galethil commented on api/src/user_refreshToken.ts
> +import { AuthenticatedRequest } from "httpd/lib";
done

2024-07-25 12:06 UTC, galethil commented on api/src/user_logout.ts
> +      const currentRefreshToken = request.cookies["refreshToken"] as string;
done

2024-07-25 12:06 UTC, galethil commented on api/src/user_refreshToken.ts
> +      if (["db", "memory"].includes(config.refreshTokenStorage as string)) {
done

2024-07-25 12:06 UTC, galethil commented on scripts/development/.env.example
> +API_DB_USER=postgres
@MartinJurcoGlina i didn't want to force admin to use the same database for both. Maybe he would like to separate the connections for each service, which is also devops security best practice.

2024-07-25 12:06 UTC, galethil commented on scripts/development/docker-compose.yml
> +      API_DB_USER: ${API_DB_USER}
@MartinJurcoGlina i didn't want to force admin to use the same database for both. Maybe he would like to separate the connections for each service, which is also devops security best practice.

2024-07-25 12:06 UTC, galethil commented on scripts/operation/.env.example
> +API_DB_USER=
@MartinJurcoGlina i didn't want to force admin to use the same database for both. Maybe he would like to separate the connections for each service, which is also devops security best practice.

2024-07-25 12:06 UTC, galethil commented on scripts/operation/docker-compose.yml
> +      API_DB_USER: {API_DB_USER}
@MartinJurcoGlina i didn't want to force admin to use the same database for both. Maybe he would like to separate the connections for each service, which is also devops security best practice.

2024-07-25 13:22 UTC, MartinJurcoGlina commented on scripts/development/.env.example
> +API_DB_USER=postgres
since we don't use DB for pretty much anything it didn't make much sense for me but ok

2024-07-25 14:18 UTC, MartinJurcoGlina commented on api/src/service/user_refresh_token.ts
> +    storedRefreshToken = getValue(`refreshToken.${refreshToken}`) as
ok, acceptable in this case

2024-07-26 19:46 UTC, MartinJurcoGlina requested changes

2024-07-29 13:57 UTC, MartinJurcoGlina approved these changes

2024-07-29 16:49 UTC, merged