DRAFT: api, frontend: added workflow mode option
openkfw/TruBudget pull request #1942
Opened 2024-08-16 10:11 UTC by SamuelPull

### Checklist

- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [ ] I fixed all necessary PR warnings
- [ ] The commit history is clean
- [ ] The E2E tests are passing
- [ ] If possible, the issue has been divided into more subtasks
- [ ] I did a self review before requesting a review from another team member

### Description

### How to test

1. <E.g. login as user XYZ>
2. <E.g. try to create new subproject>
3. <E.g. You should not see error in console>
4. ...

Closes #1829

2024-08-16 10:18 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on pipeline 60141 on remote server started</td><td>Fri, 16 Aug 2024 10:18:26 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2024-08-22 14:00 UTC, MartinJurcoGlina requested changes
after exportin into excel sheet, all subprojects have Workflow (ordere) even those I created with Unordered workflow... probably some mapping isn't working

2024-08-23 06:36 UTC, SamuelPull commented
> after exportin into excel sheet, all subprojects have Workflow (ordere) even those I created with Unordered workflow... probably some mapping isn't working

Thank you, Martin. This has been fixed.

2024-08-23 07:52 UTC, MartinJurcoGlina approved these changes

2024-08-23 07:53 UTC, merged