1583 Frontend tour
openkfw/TruBudget pull request #2112
Opened 2024-12-02 12:56 UTC by galethil

### Checklist

- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/main/.github/CONTRIBUTING.md#open-a-pull-request).
- [ ] I fixed all necessary PR warnings
- [ ] The commit history is clean
- [ ] The E2E tests are passing
- [ ] If possible, the issue has been divided into more subtasks
- [ ] I did a self review before requesting a review from another team member

### Description

### How to test

1. Open main page
2. Open main menu
3. Click on "Start tour"
4. Follow instructions
5. Try different start points, go there and back, try to break it :)

Closes #1583

2024-12-02 16:37 UTC, MartinJurcoGlina commented
any plans adding translations?

2024-12-03 08:52 UTC, pmolnar-dev commented on frontend/src/pages/Main/TourWrapper.scss
> +  min-width: 200px;
which of these min-width should be used?

2024-12-03 15:43 UTC, MartinJurcoGlina requested changes

2024-12-03 15:43 UTC, MartinJurcoGlina commented on frontend/src/pages/Main/TourWrapper.js
> +      navigateTo: "/projects"
/projects could be constant as it appears several times below

2024-12-03 15:43 UTC, MartinJurcoGlina commented on frontend/src/pages/Main/TourWrapper.js
> +      content: "Welcome to TruBudget application tour.",
all the content texts should come from translations

2024-12-03 15:43 UTC, MartinJurcoGlina commented on frontend/src/pages/SubProjects/ProjectDetails.js
> +      setTimeout(() => {
timeout should be cleared in useEffect return

2024-12-03 15:43 UTC, MartinJurcoGlina commented on frontend/src/pages/Workflows/SubProjectDetails.js
> +      setTimeout(() => {
clear timeout in return

2024-12-05 14:01 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on pipeline 61388 on remote server started</td><td>Thu, 05 Dec 2024 14:01:29 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2024-12-05 14:08 UTC, MartinJurcoGlina approved these changes

2024-12-05 14:45 UTC, merged