Update material-ui
openkfw/TruBudget pull request #565
Opened 2020-10-19 07:04 UTC by daniel-arnauer

Closes #437

2020-10-19 07:16 UTC, TruBudgetCI commented
<!--
  0 failure: 
  2 warning:  No CHANGELOG added., There were change...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>No CHANGELOG added.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>There were changes in the frontend, but no E2E-test was added or modified!</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 58a9126ee7dcb361b5a4114eaaf59d045a2f24f4
</p>

2020-10-19 07:21 UTC, TruBudgetCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Mon, 19 Oct 2020 07:21:07 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2020-10-22 11:16 UTC, Stezido requested changes
cleanup commits and rebase master then the PR can be merged

2020-10-22 12:43 UTC, daniel-arnauer commented on .travis.yml
> +    # - <<: *audit
removed

2020-10-22 13:37 UTC, Stezido approved these changes

2020-10-22 13:51 UTC, merged