added recommendation for extensions in workspace
openkfw/TruBudget pull request #594
Opened 2020-11-05 09:41 UTC by SamuelPull

Added recommended extension to workspace configuration for vscode.
Restart of vscode might be needed after pulling the changes.

`.vscode` was included in gitgnore

Issue #592

2020-11-05 09:47 UTC, TruBudgetCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Thu, 05 Nov 2020 09:47:33 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2020-11-09 10:16 UTC, georgimld approved these changes
Please edit the commit message as described in the chat

2020-11-09 10:21 UTC, georgimld requested changes
Please edit the commit message as described in the chat

2020-11-09 13:12 UTC, SamuelPull commented
Hi @georgimld, commit modified to align with guideline.

2020-11-09 13:24 UTC, georgimld approved these changes

2020-11-13 11:45 UTC, merged