Contributor guide update
openkfw/TruBudget pull request #596
Opened 2020-11-05 11:23 UTC by SamuelPull

Changes to the contribution guide were needed for successful launch in DEV mode.Necessity of changes was confirmed by new contributors also working on macs.
Although typescript is listed in dependencies, I had an older version of TS compiler installed globally and in PATH, which resulted in incorrect transpiling of source to JS, namely optional chaining wasn't recognized by node 14 (which it should?), so I added a memo.

Issue #589

2020-11-05 11:38 UTC, TruBudgetCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Thu, 05 Nov 2020 11:38:28 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2020-11-09 10:08 UTC, georgimld requested changes
As mentioned in the chat, please edit the commit messages like I described there

2020-11-09 10:58 UTC, SamuelPull commented
> As mentioned in the chat, please edit the commit messages like I described there

Reset branch and added all changes in one commit.

2020-11-09 11:06 UTC, georgimld approved these changes

2020-11-11 11:58 UTC, merged