UI: scroll back to top button added
openkfw/TruBudget pull request #609
Opened 2020-11-12 10:59 UTC by pheolink

Add Fab button at the bottom and scroll back to the top.
New file added ScrollTop.js

2020-11-12 11:01 UTC, TruBudgetCI commented
<!--
  0 failure: 
  2 warning:  No CHANGELOG added., There were change...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>No CHANGELOG added.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>There were changes in the frontend, but no E2E-test was added or modified!</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7d63aaa920f9aee58bc65239482ba2a69648c991
</p>

2020-11-12 11:06 UTC, TruBudgetCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Thu, 12 Nov 2020 11:06:13 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2020-11-13 12:50 UTC, Stezido requested changes
Good work. Consider the danger.js warnings.

2020-11-18 09:39 UTC, pheolink commented
raised a new PR
https://github.com/openkfw/TruBudget/pull/631

2020-11-18 09:39 UTC, closed without merging