frontend: Tidy up View permission dialog section
openkfw/TruBudget pull request #615
Opened 2020-11-13 12:45 UTC by m-janos

**Summary**
 * Moving from Admin section to View Permissions section
 * In Permission dialog the moving was done as following:
    * Project level:  "view permissions"  -> "View  Permission"
    * Subproject level:  "view permissions"  -> "View  Permission"
    * Workflow item level:  "view permissions"  -> "View  Permission"

**Issue**
#613

2020-11-13 12:47 UTC, TruBudgetCI commented
<!--
  0 failure: 
  2 warning:  No CHANGELOG added., There were change...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>No CHANGELOG added.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>There were changes in the frontend, but no E2E-test was added or modified!</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e55563456e23912070598394be3fdb098772c7ca
</p>

2020-11-13 12:52 UTC, TruBudgetCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Fri, 13 Nov 2020 12:52:14 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2020-11-13 13:27 UTC, Stezido requested changes
Consider danger.js warnings
- Create changelog entry
- Create e2e-test or adapt them if they already cover your changes

2020-11-26 13:29 UTC, Stezido approved these changes
Good job,
clear commit messages, clear changelog entry - code looks fine
Next time rebase the master instead of merge ;)

2020-12-01 14:00 UTC, m-janos commented
> Good job,
> clear commit messages, clear changelog entry - code looks fine
> Next time rebase the master instead of merge ;)

How nice of you :-) I still have something to learn.

2020-12-02 12:04 UTC, merged