ui: add attachment file icon in workflow
openkfw/TruBudget pull request #749
Opened 2021-01-21 08:30 UTC by pheolink

closes - #234

2021-01-21 08:36 UTC, TruBudgetCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Thu, 21 Jan 2021 08:36:32 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-01-21 09:41 UTC, georgimld requested changes
You only created tests where it is checked that the attachement icon is NOT displayed, but you should also write a test where the icon should be displayed (maybe in the documents_spec file)

2021-01-25 09:27 UTC, georgimld approved these changes

2021-02-01 13:41 UTC, Stezido submitted a review, later dismissed
Why same tests 2 times? 
Remove it from the create/edit workflowitem specs since it's not matching with create/edit it's more a view thing. 
I suggest to create a new spec named `suproject_view_details.spec`.
Also check e2e-tests they are failing

2021-02-03 11:01 UTC, georgimld approved these changes

2021-02-09 10:51 UTC, merged