725 user group edit
openkfw/TruBudget pull request #751
Opened 2021-01-21 12:25 UTC by SamuelPull

### Checklist

- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/master/CONTRIBUTING.md).

### Description

This PR adds/modifies/destroys ...

Closes ModifyMe

2021-01-21 12:30 UTC, TruBudgetCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Thu, 21 Jan 2021 12:30:37 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-02-01 09:16 UTC, Stezido requested changes
Could you please add a description what's this PR about and fix the warnings or at least describe why this warning is happening before I review the PR?

2021-02-02 12:24 UTC, SamuelPull commented on frontend/src/api.js
> +  listGroup = () => {
This can be changed back to arrow func without explicit return, probably there was logging in function body at some point.

2021-02-02 12:25 UTC, SamuelPull commented on frontend/src/pages/Common/UserSelection.js
> +  const { classes, users, addToSelection, selectedItems, handleDelete } = props;
I moved props to top of func body, nobody expects to find props deep down in React component.

2021-02-02 12:26 UTC, SamuelPull commented on frontend/src/pages/Users/Dialog.js
> -      const group = groups.find(group => group.groupId === editId);
Renamed `group` to `g`. There is already `group` in outer scope.

2021-02-02 12:43 UTC, SamuelPull commented
Rebased onto current master, modified changelog, minor formatting.

2021-02-11 17:55 UTC, Stezido reviewed
@SamuelPull I would expect that the group update can update the whole group so displayname, description, members, permissions and additionaldata. Also in the group update event I should only see what should be updated not the whole group state. so all values mentioned should be optional values like in workflowitem.update.

2021-03-04 11:55 UTC, daniel-arnauer commented
These things have to be discussed:

- Why do we need a new intent? Just change the current group.AddUser and group.RemoveUser to group.AddUsers and group.RemoveUsers, so the request does not need a single userId, instead it needs an array of userIds

- Currently, the permission "global.createGroup" is used to be allowed to execute the global.groupUpdate intent. Does this make sense? Is it possible to implement a new permission "global.groupUpdate" because of backwards compatibility?

2021-03-08 09:00 UTC, daniel-arnauer commented on api/src/service/domain/organization/group_update.ts
> +    const globalPermissionsResult = await repository.getGlobalPermissions();
why permission "global.createGroup" ?

2021-04-13 10:44 UTC, daniel-arnauer commented
This PR will be closed because this approach is not backwards compatible since here we need a new permission. 
A new, smaller approach with refactoring the current group.addMember and group.removeMember API Calls are done in PR #811

2021-04-13 10:44 UTC, closed without merging