Decline Node feature
openkfw/TruBudget pull request #776
Opened 2021-02-11 15:53 UTC by georgimld

### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/master/CONTRIBUTING.md).
- [ ] I fixed all necessary PR warnings
- [x] The commit history is clean
- [ ] The E2E tests are passing
- [x] If possible, the issue has been divided into more subtasks
- [ ] I did a self review before requesting a review from another team member

### Description

Closes #27

2021-02-17 11:41 UTC, TruBudgetCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Wed, 17 Feb 2021 11:41:09 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-02-17 15:43 UTC, georgimld commented
> Warnings
> ⚠️	It looks like an ID was added. Please make sure it is not a secret.
> ⚠️	There were changes in the frontend, but no E2E-test was added or modified!
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [4dd61d4](https://github.com/openkfw/TruBudget/commit/4dd61d4a2a90a3dc5b46b6e5a782e8e5a8970522)

2021-02-23 11:25 UTC, Stezido requested changes

2021-02-25 11:27 UTC, Stezido approved these changes

2021-02-25 13:04 UTC, merged