Refactor User selection in group editing
openkfw/TruBudget pull request #811
Opened 2021-04-13 10:42 UTC by daniel-arnauer

Currently, only one user is can be sent to add or remove a user from a group. For better performance, send a array of user ids to the API

- [ ] Refactor group.addMember in API
- [ ] Refactor group.removeMember in API
- [ ] Refactor Unit tests in API
- [ ] Refactor UI
- [ ] Refactor provisioning?
- [ ] Refactor e2e-tests?

Closes #725

2021-04-13 10:47 UTC, TruBudgetCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Tue, 13 Apr 2021 10:47:39 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-06-08 09:18 UTC, Stezido commented
Closing PR - other focus (RoadMap)

2022-05-10 09:42 UTC, mayrmartin commented on api/src/index.ts
> -  removeGroupMember: (ctx, issuer, groupId, newMember) =>
good catch 😉

2022-05-10 09:55 UTC, mayrmartin requested changes
since endpoints changed pls update load-test endpoints (can be generated via API specification)

2022-05-10 09:55 UTC, mayrmartin commented on api/src/service/domain/organization/group_eventsourcing.ts
> +  group.members.push(...newMembers);
use array.reduce

2022-05-10 09:55 UTC, mayrmartin commented on api/src/service/domain/organization/group_eventsourcing.ts
> +  });
consider using via map & filter

```

export function remove(...itemsToRemoe) {
    return this.filter(item => !itemsToRemoe.includes(item))
}

const toRemove = membersRemoved.members.map(member => group.members.indexOf(member)).filter(idx => idx !==  - 1);

const result = group.members::remove(toRemove)
```

2022-05-11 07:10 UTC, daniel-arnauer commented on api/src/service/domain/organization/group_eventsourcing.ts
> +  group.members.push(...newMembers);
done

2022-05-11 07:10 UTC, daniel-arnauer commented on api/src/service/domain/organization/group_eventsourcing.ts
> +  });
done

2022-05-11 07:22 UTC, mayrmartin approved these changes

2022-05-11 13:32 UTC, merged