Add e2e-tests and api tests for doc-feature
openkfw/TruBudget pull request #829
Opened 2021-06-07 11:51 UTC by daniel-arnauer

- [ ] Add e2e-tests
- [ ] Add API tests

follow up issue to #809

2021-06-07 11:59 UTC, TruBudgetCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Mon, 07 Jun 2021 11:59:29 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-06-22 06:52 UTC, daniel-arnauer commented on api/src/service/document_upload.ts
>            getDocumentsEvents: async () => {
await is unnecessary - removed by eslint

2021-06-24 15:23 UTC, georgimld commented on api/src/service/domain/document/document_share.spec.ts
> +  it("User must belong to the same organization", async () => {
test should be deleted once this check is fixed in `document_share`

2021-06-25 14:15 UTC, georgimld requested changes

2021-06-25 14:15 UTC, georgimld commented on api/src/service/domain/organization/public_key_update.spec.ts
> +    it("Updating a public key of an existing organization works", async () => {
can this be tested already?

2021-07-05 15:33 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Mon, 05 Jul 2021 15:33:36 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-07-06 10:16 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Tue, 06 Jul 2021 10:16:46 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-07-06 13:47 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Tue, 06 Jul 2021 13:47:18 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-07-07 12:02 UTC, daniel-arnauer commented on api/src/service/domain/document/document_download.spec.ts
> +    assert.isTrue(Result.isOk(result));
remove console log

2021-07-07 12:41 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Wed, 07 Jul 2021 12:41:20 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-07-07 14:49 UTC, georgimld approved these changes

2021-07-07 15:39 UTC, merged