WIP: ui/api: add possibility to reject workflowitem
openkfw/TruBudget pull request #929
Opened 2021-08-13 14:22 UTC by mayrmartin

### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/master/CONTRIBUTING.md).
- [x] I fixed all necessary PR warnings
- [x] The commit history is clean
- [ ] The E2E tests are passing
- [x] If possible, the issue has been divided into more subtasks
- [x] I did a self review before requesting a review from another team member

### Description
Adds possibility to reject workflowitems
Closes #845 #848 #920 #918

2021-08-17 12:55 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Tue, 17 Aug 2021 12:55:43 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-08-18 08:18 UTC, daniel-arnauer commented on frontend/src/sagas.js
> +    if (confirmed !== true) {
Do not fetch rejectReason directly. Instead, move it to the paramater list in line 2332.

See assignProjectSaga for reference. There, the assigneeDisplayName is also forwarded through the paramater list

2021-08-18 08:19 UTC, daniel-arnauer commented on frontend/src/pages/Confirmation/ConfirmationContainer.js
>    };
change val to rejectReason

2021-08-18 08:19 UTC, daniel-arnauer commented on frontend/src/pages/Confirmation/ConfirmationContainer.js
> +
Add rejectReason as parameter to rejectWorkflowItem

2021-08-18 08:25 UTC, daniel-arnauer commented
If the workflowitem was rejected, the status should be "Rejected" instead of "Closed". Maybe the rejectReason should be mentioned in this component as well.

![image](https://user-images.githubusercontent.com/59825636/129864213-ef6184d6-2aca-4474-9ce7-e44f77a79d3e.png)

2021-08-18 09:44 UTC, daniel-arnauer requested changes

2021-08-18 09:44 UTC, daniel-arnauer commented on e2e-test/cypress/integration/workflowitem_reject_spec.js
> +      .click();
Using .last and .first is a bit hacky. A better solution is to add the workflowitemId to data-test, so the component can be used explicitly.

2021-08-18 09:44 UTC, daniel-arnauer commented on e2e-test/cypress/integration/workflowitem_types_spec.js
> +          // show-workflowitem-permissions not shown anymore when workflowSortEnabled || permissionsDisabled
try using .should("not.exist");

2021-08-18 09:44 UTC, daniel-arnauer commented on e2e-test/cypress/integration/workflowitem_types_spec.js
> +          // show-workflowitem-permissions not shown anymore when workflowSortEnabled || permissionsDisabled
and remove the comment

2021-08-18 09:44 UTC, daniel-arnauer commented on frontend/src/languages/german.js
>      search: "German: Search",
Why is there a space? Also check other translations for that

2021-08-18 09:44 UTC, daniel-arnauer commented on frontend/src/pages/Confirmation/ConfirmationDialog.js
> +        };
As I mentioned in sagas.js, remove this since this intent does not exist. Instead, update "workflowitem.close"

2021-08-18 09:44 UTC, daniel-arnauer commented on frontend/src/pages/Workflows/reducer.js
> +  rejectReasonDialogContent: undefined
rename `rejectReasonDialogContent` to `isRejectReasonDialogShown`

2021-08-18 09:44 UTC, daniel-arnauer commented on frontend/src/pages/Workflows/WorkflowContainer.js
> +            dialogShown={this.props.rejectReasonDialogContent ? true : false}
use a boolean var here

2021-08-18 09:44 UTC, daniel-arnauer commented on frontend/src/pages/Workflows/WorkflowContainer.js
> +            content={this.props.rejectReasonDialogContent ? <Typography>{this.props.rejectReasonDialogContent}</Typography> : ''}
I dont thing an extra variable is necessary here. The rejectReason should be in workflowItems[] if its rejected. This is fetched on FETCH_ALL_SUBPROJECT_DETAILS_SUCCESS

2021-08-18 09:44 UTC, daniel-arnauer commented on frontend/src/pages/Workflows/WorkflowItem.js
> +          data-test="closed-workflowitem-rejct-reason"
typo

2021-08-18 09:44 UTC, daniel-arnauer commented on frontend/src/pages/Workflows/WorkflowItem.js
> +            onClick={closeDisabled ? undefined : reject}
Here you have 2 conditions in line 465 and 468. Only use 1. Moreover, move the conditions to up to line 422 and give it a name that makes sense to see the business rule immediately

2021-08-18 09:44 UTC, daniel-arnauer commented on frontend/src/pages/Workflows/WorkflowItem.js
> +            onClick={closeDisabled ? undefined : reject}
Do this for the other vars in the file too

2021-08-18 13:28 UTC, mayrmartin commented on api/src/service/domain/workflow/workflowitem.ts
>      status: workflowitem.status,
@Stezido ?

2021-08-23 08:53 UTC, daniel-arnauer commented on frontend/src/pages/Workflows/actions.js
> +}
Make two functions without paramater list: `showReasonDialog` and `hideReasonDialog` . Your version is too confusing

2021-08-23 08:53 UTC, daniel-arnauer commented on frontend/src/pages/Workflows/reducer.js
> +  isRejectReasonDialogShown: undefined
default for `isRejectReasonDialogShown` is false. Undefined should never be used for this because `is` implies a boolean var

2021-08-23 08:53 UTC, daniel-arnauer commented on frontend/src/sagas.js
> +const getWorkflowitemReject = state => {
change to `getWorkflowitemRejectReason`

2021-08-23 08:53 UTC, daniel-arnauer commented on frontend/src/api.js
> +  closeWorkflowItem = (projectId, subprojectId, workflowitemId,rejectReason) => {
change to `closeWorkflowItem = (projectId, subprojectId, workflowitemId,rejectReason = "")` to provide a default value

2021-08-23 08:53 UTC, daniel-arnauer commented on frontend/src/api.js
> +      instance.post(`/workflowitem.close`, {
add comment: // Workflowitem approved

2021-08-23 08:53 UTC, daniel-arnauer commented on frontend/src/api.js
>      instance.post(`/workflowitem.close`, {
add comment: // Workflowitem rejected with rejectReason

2021-08-24 16:22 UTC, daniel-arnauer approved these changes

2021-08-24 16:22 UTC, merged