Fix simultaneous document upload
openkfw/TruBudget pull request #975
Opened 2021-09-07 09:41 UTC by daniel-arnauer

### Description

Closes #972

2021-09-07 10:58 UTC, openkfwCI commented
<!-- E2EID:E2E_TEST --><table><thead><tr><th width="50"></th><th width="60%">Notes</th><th width="40%">Time</th></tr></thead><tbody><tr><td>:grey_exclamation:</td><td>Note for Reviewer: E2E tests on remote server started</td><td>Tue, 07 Sep 2021 10:58:24 +0000</td></tr></tbody></table><p align="right">Generated by E2E-Test</p>

2021-09-07 11:24 UTC, daniel-arnauer commented on api/src/service/domain/workflow/project_permission_revoke.ts
> +    project?.permissions[intent]?.length === 1
This fixes a new compiler error ["object could be undefined"]

2021-09-07 14:03 UTC, daniel-arnauer commented on api/src/service/Client_storage_service.ts
> +      return new VError(result, "downloading object failed");
rewrite Verror message

2021-09-20 13:41 UTC, daniel-arnauer commented on storage-service/src/minio.ts
> -}
This is dead code

2021-09-20 14:03 UTC, georgimld requested changes

2021-09-20 14:03 UTC, georgimld commented on storage-service/src/minio.ts
> -const makeBucketAsPromised = (bucket: string) => {
This should be used on storage service start

2021-09-20 14:03 UTC, georgimld commented on storage-service/src/minio.ts
> -const makeBucketAsPromised = (bucket: string) => {
Right now,  `establishConnection()` is not used anywhere

2021-09-21 09:27 UTC, georgimld approved these changes

2021-09-21 09:29 UTC, merged